
import json

file_path = 'c:/shin_working/war/military-platform/scripts/complete_military_data.json'

with open(file_path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Target line index (0-indexed)
# Line 256 in 1-indexed view is index 255
target_idx = 255

# Verify target line
if "afv" in lines[target_idx] and "2000" in lines[target_idx]:
    print(f"Found target line at {target_idx}: {lines[target_idx].strip()}")
    
    # Construct insertion block
    insertion = [
        '            "trainers": 150,\n',
        '            "specialMission": 40,\n',
        '            "tankerFleet": 15,\n',
        '            "helicopters": 400,\n',
        '            "attackHelicopters": 67,\n',
        '            "bombers": 0\n',
        '        },\n',
        '        "nuclear": {\n',
        '            "hasNuclear": true,\n',
        '            "stockpile": 290\n',
        '        }\n',
        '    },\n',
        '    "JPN": {\n',
        '        "army": {\n',
        '            "activePersonnel": 247000,\n',
        '            "reservePersonnel": 56000,\n',
        '            "tanks": 500,\n',
        '            "afv": 5000,\n',
        '            "selfPropelledArtillery": 200,\n',
        '            "towedArtillery": 300,\n',
        '            "rocketProjectors": 50\n',
        '        },\n',
        '        "navy": {\n',
        '            "totalShips": 155,\n',
        '            "aircraftCarriers": 2,\n',
        '            "submarines": 22,\n',
        '            "destroyers": 36,\n',
        '            "frigates": 10,\n',
        '            "corvettes": 6,\n',
        '            "patrolVessels": 6,\n',
        '            "merchantMarine": 5000,\n',
        '            "majorPorts": 20\n',
        '        },\n',
        '        "airforce": {\n',
        '            "totalAircraft": 1400,\n',
        '            "fighters": 280,\n',
        '            "attackAircraft": 0,\n',
        '            "transports": 60,\n',
        '            "trainers": 400,\n',
        '            "specialMission": 50,\n',
        '            "tankerFleet": 6,\n',
        '            "helicopters": 500,\n',
        '            "attackHelicopters": 80,\n',
        '            "bombers": 0\n',
        '        },\n',
        '        "nuclear": {\n',
        '            "hasNuclear": false,\n',
        '            "stockpile": 0\n',
        '        }\n',
        '    },\n',
        '    "TUR": {\n',
        '        "army": {\n',
        '            "activePersonnel": 355200,\n',
        '            "reservePersonnel": 378700,\n',
        '            "tanks": 2229,\n',
        '            "afv": 11000,\n',
        '            "selfPropelledArtillery": 1038,\n',
        '            "towedArtillery": 1200,\n',
        '            "rocketProjectors": 600\n',
        '        },\n',
        '        "navy": {\n',
        '            "totalShips": 154,\n',
        '            "aircraftCarriers": 1,\n',
        '            "submarines": 12,\n',
        '            "destroyers": 0,\n',
        '            "frigates": 16,\n',
        '            "corvettes": 10,\n',
        '            "patrolVessels": 35,\n',
        '            "merchantMarine": 1200,\n',
        '            "majorPorts": 10\n',
        '        },\n',
        '        "airforce": {\n',
        '            "totalAircraft": 1065,\n',
        '            "fighters": 243,\n',
        '            "attackAircraft": 0,\n',
        '            "transports": 83,\n',
        '            "trainers": 275,\n',
        '            "specialMission": 20,\n',
        '            "tankerFleet": 7,\n',
        '            "helicopters": 500,\n',
        '            "attackHelicopters": 111,\n',
        '            "bombers": 0\n',
        '        },\n',
        '        "nuclear": {\n',
        '            "hasNuclear": false,\n',
        '            "stockpile": 0\n',
        '        }\n',
        '    },\n',
        '    "ITA": {\n',
        '        "army": {\n',
        '            "activePersonnel": 165500,\n',
        '            "reservePersonnel": 18300,\n',
        '            "tanks": 200,\n',
        '            "afv": 4000,\n',
        '            "selfPropelledArtillery": 150,\n',
        '            "towedArtillery": 100,\n',
        '            "rocketProjectors": 21\n',
        '        },\n',
        '        "navy": {\n',
        '            "totalShips": 143,\n',
        '            "aircraftCarriers": 2,\n',
        '            "submarines": 8,\n',
        '            "destroyers": 4,\n',
        '            "frigates": 12,\n',
        '            "corvettes": 0,\n',
        '            "patrolVessels": 16,\n',
        '            "merchantMarine": 1400,\n',
        '            "majorPorts": 18\n',
        '        },\n',
        '        "airforce": {\n',
        '            "totalAircraft": 800,\n',
        '            "fighters": 185,\n',
        '            "attackAircraft": 30,\n',
        '            "transports": 30,\n',
        '            "trainers": 150,\n',
        '            "specialMission": 25,\n',
        '            "tankerFleet": 10,\n',
        '            "helicopters": 400,\n',
        '            "attackHelicopters": 60,\n',
        '            "bombers": 0\n',
        '        },\n',
        '        "nuclear": {\n',
        '            "hasNuclear": false,\n',
        '            "stockpile": 0\n',
        '        }\n',
        '    },\n',
        '    "BRA": {\n',
        '        "army": {\n',
        '            "activePersonnel": 360000,\n',
        '            "reservePersonnel": 1340000,\n',
        '            "tanks": 290,\n'
    ]
    
    # New lines: 0 to 255 (inclusive) + insertion + 256 to end
    new_lines = lines[:target_idx] + insertion + lines[target_idx:]
    
    with open(file_path, 'w', encoding='utf-8') as f:
        f.writelines(new_lines)
    
    print("Successfully patched file.")
else:
    print(f"Target line mismatch at {target_idx}: {lines[target_idx].strip()}")
