
import os

file_path = r'c:\shin_working\war\military-platform\src\lib\tacticsData.ts'

translations = {
    # Names (Neutral Air Superiority remainder)
    "조기 경보 체제": "Early Warning System",
    "EMP 억제": "EMP Suppression",
    "영공 침범 경고": "Airspace Violation Warning",
    "전자파 수집": "Electronic Signal Collection",
    "공중 충돌 방지": "Aerial Collision Avoidance",
    "기상 조작 정찰": "Weather Control Recon",
    "드론 감시망": "Drone Surveillance Network",
    "공중 위력 시위": "Aerial Power Demo",
    "무인 정찰기 살포": "UAV Swarm",
    "항공 통제": "Air Traffic Control",
    "신호 정보 수집": "SIGINT Collection",

    # Descriptions (Defensive & Neutral)
    "주요 진입로에 다층적인 참호와 콘크리트 벙커를 건설하여 적의 전진을 막습니다. 적이 막대한 피해를 보지 않고서는 한 걸음도 뗄 수 없게 만듭니다.": "Construct multi-layered trenches and concrete bunkers on key approach routes. Make every step forward costly for the enemy.",
    "후퇴하면서 적군이 활용할 수 있는 모든 물자와 식량, 건물을 파괴합니다. 점령한 땅에서 아무것도 얻지 못한 적군이 보급난에 빠지게 유도합니다.": "Destroy all usable supplies, food, and buildings while retreating. Leave nothing for the enemy, forcing them into a supply crisis.",
    "지하 통로로 연결된 요새들을 구축하여 적의 폭격에도 부대를 온전히 보존합니다. 지상에서는 보이지 않지만 언제든 역습을 가할 수 있는 요새군입니다.": "Build interconnected underground fortresses to preserve forces from bombing. Invisible from above, but ready to counter-attack at any time.",
    "한 줄의 방어선이 뚫리더라도 뒤에 수많은 방어선이 대기하는 겹겹의 방어 체계를 갖춥니다. 적의 공격 에너지를 전진할수록 소진시키는 전략입니다.": "Establish a deep, multi-layered defense system. As the enemy breaches one line, they face another, exhausting their momentum.",
    "일반 도시의 모든 건물을 방어 거점으로 개조하여 시가전을 유도합니다. 적군이 미로 같은 도시에서 보이지 않는 저격수와 함정에 소모되게 만듭니다.": "Convert city buildings into defense points to force urban combat. Wear down the enemy in a maze of snipers and traps.",
    "일반 시민들을 무장시켜 정규군과 함께 방어전에 투입합니다. 압도적인 수적 열세를 머릿수로 극복하며 적의 점령 속도를 늦춥니다.": "Arm civilians to fight alongside the regular army. Overcome numerical inferiority with sheer numbers and slow the occupation.",
    "승리보다는 적의 진격 속도를 늦추는 데 집중하여 시간을 법니다. 그 사이 우방국의 지원을 받거나 강력한 반격 무기를 준비합니다.": "Focus on slowing enemy advance rather than winning, to buy time. Use the delay to get ally support or prepare counter-weapons.",
    "전략적으로 포기할 수 없는 요충지에 정예병을 배치하여 끝까지 저항합니다. 적의 발을 묶어두어 다른 전선의 아군이 재정비할 기회를 제공합니다.": "Deploy elite troops to hold key strategic points at all costs. Tie down the enemy to allow friendly forces elsewhere to regroup.",
    "적의 예상 진로에 대량의 대인 및 대전차 지뢰를 매설합니다. 지뢰밭에 발이 묶인 적군을 장거리 포격으로 섬멸하는 방식입니다.": "Lay massive minefields on expected enemy routes. Trap the enemy in the fields and destroy them with long-range artillery.",
    "전 국민과 핵심 설비를 지하로 대피시켜 적의 전략 폭격 효과를 무력화합니다. 국가의 핵심 기능을 유지하며 장기전으로 끌고 갑니다.": "Evacuate citizens and key facilities underground to neutralize strategic bombing. Maintain core state functions for a protracted war.",
    "적의 공격을 받는 주요 도로 대신 비밀리에 구축한 보급로를 통해 물자를 공급합니다. 전선이 고립되는 것을 막고 지속적인 저항 능력을 확보합니다.": "Supply via secret routes instead of targeted main roads. Prevent isolation and ensure sustained resistance capability.",
    "적의 공세가 가장 치열할 때 힘을 비축했다가, 적이 지친 순간을 노려 반격을 가합니다. 수비의 끝을 공격으로 장식하여 전세를 역전시키는 작전입니다.": "Conserve strength during peak enemy offense, then counter-attack when they tire. Turn the tables by ending defense with a strike.",
    "점령당한 지역 뒤편에서 소규모 부대를 운영해 적의 후방을 계속 괴롭힙니다. 적군이 점령지를 안정화하지 못하게 만들어 병력을 분산시키게 합니다.": "Operate small units behind lines to harass enemy rear. Prevent occupation stabilization and force enemy dispersion.",
    "모든 방어 진지에 대공포와 지대공 미사일을 촘촘히 배치합니다. 적의 항공 지원을 원천 차단하여 지상군끼리의 공정한(?) 대결을 강요합니다.": "Deploy dense AA guns and SAMs at all defense sites. Deny air support, forcing a 'fair' ground-only fight.",
    "위장막과 기만 시설을 활용해 공장이나 지휘소를 평범한 건물처럼 보이게 합니다. 적의 폭탄이 엉뚱한 곳에 낭비되도록 유도하는 기만술입니다.": "Camouflage factories and command posts as normal buildings. Deceive the enemy into wasting bombs on wrong targets.",
    "지형이 불리할 때는 과감히 후퇴하여 더 유리한 방어 지점으로 적을 끌어들입니다. 적의 보급선은 늘리고 아군의 보급선은 짧게 만드는 효과가 있습니다.": "Retreat from bad terrain to lure enemy to better defense spots. Extends enemy supply lines while shortening friendly ones.",
    "고정된 방어선에 머물지 않고 적의 공격 지점에 맞춰 방어 병력을 빠르게 이동시킵니다. 유연한 대응으로 적의 집중 타격을 회피하며 방어력을 유지합니다.": "Move defense forces rapidly to match enemy attack points instead of staying static. Flexibly evade concentrated strikes.",
    "모든 병사에게 사수 명령을 내려 한 사람도 물러서지 않고 싸우게 합니다. 극단적인 정신 무장을 통해 적에게 심리적 경외심과 피로감을 줍니다.": "Order 'No Retreat' to all soldiers. Create psychological awe and fatigue in the enemy through extreme mental fortitude.",
    "전쟁 전부터 산더미 같은 식량과 탄약을 전국 곳곳에 숨겨둡니다. 외부 보급이 끊기더라도 수년 동안 자력으로 버틸 수 있는 환경을 만듭니다.": "Hide stockpiles of food and ammo nationwide before war. Enable years of self-sufficiency even if cut off.",
    "방어선 일부를 일부러 약하게 만들어 적을 깊숙이 유인한 뒤, 사방에서 포위하여 섬멸합니다. 적의 승리감을 이용해 패배를 안겨주는 고도의 함정입니다.": "Weaken part of the line to lure enemy deep, then encircle and destroy. A sophisticated trap exploiting enemy confidence.",

    "해안 절벽과 요새에 강력한 대함포를 배치해 접근을 막습니다.": "Deploy powerful anti-ship guns on coastal cliffs and forts to block access.",
    "아군 항구 주변을 기뢰로 도배하여 적 함선의 진입을 물리적으로 차단합니다.": "Mine friendly harbors to physically block enemy ship entry.",
    "소나와 초계기를 총동원해 잠수함의 침투를 24시간 감시합니다.": "Mobilize all sonar and patrol planes for 24/7 sub infiltration monitoring.",
    "구축함으로 상선들을 겹겹이 에워싸 약탈을 막아냅니다.": "Surround merchant ships with destroyers to prevent looting.",
    "얕은 바다의 이점을 살려 소형함들이 적 대형함을 농락합니다.": "Use small ships to outmaneuver large enemy vessels in shallow waters.",
    "바다 밑바닥에 감지기를 깔아 적의 움직임을 실시간으로 읽습니다.": "Lay seabed sensors to track enemy movements in real-time.",
    "바다 한가운데 요새화된 섬을 만들어 방어 반경을 넓힙니다.": "Build fortified islands in the middle of the sea to extend defense range.",
    "최악의 경우 스스로 선박을 침몰시켜 항구 입구를 막아버립니다.": "Scuttle ships to block harbor entrances in worst-case scenarios.",
    "무수한 미사일 고속정을 배치해 적이 다가오면 벌떼처럼 공격합니다.": "Deploy swarms of missile boats to attack approaching enemies like bees.",
    "상륙이 가능한 해변에 거대한 콘크리트 장벽과 장애물을 설치합니다.": "Install huge concrete walls and obstacles on landable beaches.",
    "해안선 근처의 야간 순찰을 강화해 소규모 침투조를 막습니다.": "Strengthen night patrols near coastline to stop small infiltration teams.",
    "피해를 본 아군 함선에서 병력을 신속히 구조해 전력 손실을 줄입니다.": "Rapidly rescue troops from damaged ships to minimize force loss.",
    "전투함 일부를 보급선 전담 경호팀으로 지정해 안정성을 높입니다.": "Assign combat ships specifically to escort supply vessels for stability.",
    "적 잠수함이 통과할 수 없는 거대한 그물과 장벽을 수중에 설치합니다.": "Install nets and barriers underwater that subs cannot pass.",
    "무장한 해양 경찰과 경비정을 동원해 촘촘한 감시망을 유지합니다.": "Mobilize armed coast guard and cutters to maintain a tight watch.",
    "최신 대잠 헬기를 운용해 적 잠수함을 끝까지 추격해 부상시킵니다.": "Use modern ASW helis to hunt subs until they surface.",
    "국제법을 강조하며 적의 진입이 불법임을 전 세계에 알립니다.": "Highlight international law and declare enemy entry effectively illegal to the world.",
    "항구 주변 건물을 포대로 개조해 최후의 항전 준비를 합니다.": "Convert port buildings into batteries for last stand preparation.",
    "산속 깊이 숨겨진 미사일 차량으로 언제든 적 함대를 저격합니다.": "Snipe enemy fleets anytime with missile vehicles hidden deep in mountains.",
    "중앙에 대기하다가 적이 나타난 지점으로 즉각 출동해 방어합니다.": "Wait in center, then immediately deploy to wherever enemy appears.",

    "국경 전체를 가로지르는 철옹성을 쌓아 물리적 진입을 막습니다.": "Build a massive wall across the border to physically prevent entry.",
    "주요 도로마다 요새를 건설해 적 전차의 통행을 원천 봉쇄합니다.": "Build forts on key roads to block enemy tank passage completely.",
    "적이 국경을 넘도록 유도한 뒤 미리 준비된 사격 구역에서 섬멸합니다.": "Lure enemy across border, then destroy in prepared kill zones.",
    "적이 국경 인근에 집결하면 즉시 타격할 수 있는 미사일을 대기시킵니다.": "Ready missiles to strike immediately if enemy gathers near border.",
    "최정예 병력을 국경에 상시 배치해 즉각 대응 체계를 갖춥니다.": "Station elite troops at border permanently for immediate response.",
    "적의 전파 방해에 대비해 독자적인 보안 통신망을 강화합니다.": "Strengthen secure comms network against enemy jamming.",
    "국경 인근 민간인의 출입을 제한해 간첩 침투를 차단합니다.": "Restrict civilian access near border to stop spy infiltration.",
    "고성능 CCTV와 센서로 국경의 모든 움직임을 모니터링합니다.": "Monitor all border movement with high-performance CCTV and sensors.",
    "적이 국경에 접근하면 경고의 의미로 정밀 포격을 가합니다.": "Fire precision warning shots if enemy approaches border.",
    "적이 올 수밖에 없는 길목에 대량의 지뢰를 깔아 진격을 늦춥니다.": "Lay mines on inevitable paths to slow enemy advance.",
    "완충 지대의 평화를 유지하며 적의 도발 명분을 제거합니다.": "Maintain peace in buffer zone to remove enemy pretext for provocation.",
    "헬기를 이용해 국경 어느 곳이든 10분 내로 증원군을 보냅니다.": "Send reinforcements anywhere on border within 10 mins using helis.",
    "모든 출입 인원과 차량을 철저히 검사해 파괴 분자를 색출합니다.": "Inspect all people and vehicles thoroughly to catch saboteurs.",
    "적 특수부대가 넘을 수 없는 센서 벽을 설치합니다.": "Install sensor walls that enemy special forces cannot cross.",
    "사각지대 없는 감시를 위해 수많은 무인 관측소를 운영합니다.": "Operate numerous unmanned posts for blind-spot-free surveillance.",
    "전차의 진입을 막는 '용치'와 철조망을 겹겹이 배치합니다.": "Layer 'dragon's teeth' and barbed wire to block tanks.",
    "아군 국경 수비대의 무전을 적이 도청하지 못하게 암호화합니다.": "Encrypt friendly border guard comms to prevent eavesdropping.",
    "침입 발생 시 전 지역에 즉시 비상 사이렌을 울려 대비합니다.": "Sound emergency sirens everywhere immediately upon intrusion.",
    "험준한 산악 지형을 방패 삼아 소수 병력으로 대군을 막습니다.": "Use rough mountain terrain as a shield to stop large armies with few troops.",
    "자폭 기능이 아닌 정찰과 경고 기능을 가진 드론으로 국경을 지킵니다.": "Guard border with drones for recon/warning, not suicide attacks.",

    "미식별 항공기가 근처에 오면 즉시 요격기를 출격시킵니다.": "Scramble interceptors immediately if unidentified aircraft approach.",
    "하늘 전체를 뒤덮을 정도의 미사일 방어망을 구축합니다.": "Build a missile defense net covering the entire sky.",
    "조종사들이 콕핏 안에서 대기하며 5분 내 이륙 태세를 유지합니다.": "Pilots wait in cockpits, ready to takeoff in 5 mins.",
    "적의 스텔스기까지 잡아낼 수 있는 다파장 레이더를 운영합니다.": "Operate multi-wavelength radar capable of catching stealth jets.",
    "가짜 전투기 모형을 배치해 적 폭격기의 헛수고를 유도합니다.": "Deploy dummy fighters to trick enemy bombers.",
    "전투기를 지하 격납고나 산속 동굴에 숨겨 보존합니다.": "Hide fighters in underground hangars or caves.",
    "미사일 차량을 계속 이동시켜 적의 선제 타격을 피합니다.": "Keep missile vehicles moving to avoid pre-emptive strikes.",
    "적의 방공망을 피해 아군기가 안전하게 이동할 통로를 지킵니다.": "Secure a corridor for friendly planes to avoid enemy air defense.",
    "적의 유도 미사일을 무력화하는 강력한 재밍 신호를 방출합니다.": "Emit strong jamming signals to neutralize enemy guided missiles.",
    "아군 영공에 들어온 적기만 골라 격추하며 세력을 보존합니다.": "Shoot down only intruding enemy planes to conserve strength.",
    "육해공의 모든 레이더 정보를 통합해 효율적으로 요격합니다.": "Integrate land/sea/air radar info for efficient interception.",
    "적의 미사일을 공중에서 맞추는 미사일 방어 체계(MD)를 가동합니다.": "Activate Missile Defense (MD) to hit enemy missiles in the air.",
    "특정 지역을 비행 금지 구역으로 선포하고 진입 시 무조건 격추합니다.": "Declare No-Fly Zone and shoot down anything entering it.",
    "미사일이 놓친 적기를 위해 촘촘한 기관포 방어망을 운영합니다.": "Operate dense AA gun nets for planes that missiles miss.",
    "적의 전자전 공격 속에서도 아군기끼리의 통신을 유지합니다.": "Maintain friendly plane comms even under enemy EW attack.",
    "기지 주변을 견고한 요새로 만들어 지상 공격으로부터 보호합니다.": "Fortify base perimeter against ground attacks.",
    "적기가 뜨는 순간 전 국민에게 공습경보를 전달합니다.": "Broadcast air raid warning to public the moment enemy takes off.",
    "파괴된 레이더나 미사일 기지를 즉시 수리해 방어 공백을 메웁니다.": "Repair destroyed radars/bases immediately to fill defense gaps.",
    "전쟁 초기에는 전투기를 아껴뒀다가 결정적인 순간에 출격시킵니다.": "Save fighters early in war, launch at decisive moment.",
    "적 폭격기가 목표에 닿기 전 자살 특공에 가까운 요격을 감행합니다.": "Intercept enemy bombers with near-suicidal attacks before they reach targets.",

    "전면전 대신 국경 인근에서 대규모 훈련을 열어 적의 공격을 억제합니다.": "Hold massive drills near border instead of war to deter attack.",
    "적과 아군 사이에 중립 지대를 설정해 직접적인 충돌을 피합니다.": "Set neutral zone to avoid direct conflict.",
    "작은 요충지 하나만 점령한 뒤 이를 지렛대 삼아 유리한 평화 협상을 제안합니다.": "Occupy just one key point for leverage in peace talks.",
    "국제 기구의 승인을 얻어 제3국 군대를 전선에 배치해 전쟁을 멈춥니다.": "Deploy 3rd party troops with UN approval to stop war.",
    "적이 공격한 만큼만 똑같이 되돌려주어 확전을 방지하고 경고를 보냅니다.": "Retaliate exactly in kind to prevent escalation and send warning.",
    "총 대신 경제적 압박을 가해 적이 스스로 전쟁을 포기하게 유도합니다.": "Use economic pressure instead of guns to force enemy surrender.",
    "적의 도발에도 즉각 대응하지 않고 국제 사회의 여론이 우리 편이 될 때까지 기다립니다.": "Wait for international opinion to shift instead of reacting to provocation.",
    "적국을 국제 사회에서 악당으로 몰아세워 우방국들이 돕지 못하게 만듭니다.": "Paint enemy as villains globally so allies won't help them.",
    "적의 내부 정보를 유출시켜 적국 시민들이 전쟁에 반대하게 만듭니다.": "Leak enemy internal info to turn their citizens against war.",
    "민간인들을 위해 길을 열어주어 전쟁의 비극을 최소화하고 명분을 쌓습니다.": "Open humanitarian corridors to minimize tragedy and build moral high ground.",
    "전력이 팽팽할 때 제3자의 중재를 요청해 전쟁을 조기에 끝냅니다.": "Request mediation when power is balanced to end war early.",
    "적국 내부의 온건파를 지원해 주전파 지휘부를 교체하도록 유도합니다.": "Support enemy moderates to replace hawkish leadership.",
    "미디어를 활용해 아군의 방어 정당성을 홍보하고 지원을 끌어냅니다.": "Use media to promote defense legitimacy and attract support.",
    "\"공격하면 너도 죽는다\"는 핵전력이나 강력한 무기를 보여주며 평화를 유지합니다.": "Maintain peace by showing MAD capacity: 'Attack and you die too'.",
    "전면전 대신 요인 암살이나 주요 시설 파괴 등 보이지 않는 전쟁을 치릅니다.": "Wage invisible war (assassination/sabotage) instead of total war.",
    "아군 영토에 제3국 군대가 주둔하게 하여 적의 공격 명분을 없앱니다.": "Host 3rd party troops to remove enemy attack pretext.",
    "어느 한쪽이 너무 강해지지 않게 힘을 조절하며 소모전을 유도합니다.": "Control power balance to induce attrition warfare without a clear winner.",
    "전쟁 중에도 적국 수뇌부와 언제든 대화할 수 있는 '핫라인'을 유지합니다.": "Maintain 'hotline' with enemy leaders even during war.",
    "강대국 사이의 전쟁에서 어느 편도 들지 않고 영토 침범만 막습니다.": "Take no side in great power war, only stop territory breach.",
    "우발적 충돌이 큰 전쟁으로 번지지 않게 현장에서 즉시 불을 끕니다.": "Extinguish accidental clashes immediately on site to prevent war.",

    "무기가 아닌 식량이나 생필품을 실은 배는 통과시켜 국제적 비난을 피합니다.": "Let food/necessities pass to avoid international condemnation.",
    "공해상에서의 무질서한 전투를 막고 평화적인 항행권을 보호합니다.": "Stop chaotic fighting in high seas and protect navigation rights.",
    "적함 근처 바다에 포를 쏴서 더 이상 다가오지 말라는 신호를 보냅니다.": "Fire warning shots near enemy ships to signal 'keep away'.",
    "봉쇄 구역 대신 더 멀지만 안전한 다른 길로 가라고 상선들에게 안내합니다.": "Guide merchants to safer, longer routes avoiding blockade.",
    "의심스러운 배만 세워서 조사하고, 문제가 없으면 사과와 함께 보내줍니다.": "Stop only suspicious ships; apologize and release if clean.",
    "특정 해역을 전투 금지 구역으로 선포하고 누구든 진입하면 퇴거시킵니다.": "Declare sea zone as 'No Combat' and evict any entrants.",
    "해적을 잡는다는 핑계로 군함을 배치해 자연스럽게 해역을 통제합니다.": "Deploy warships under pretext of anti-piracy to control seas.",
    "싸우지 않고 적 함대 앞에 아군 함대를 배치해 길을 막고 버팁니다.": "Block enemy path with fleet without fighting, just standing off.",
    "공격 무기 없이 정찰기만 띄워 적의 움직임을 모두 기록하고 공개합니다.": "Launch only recon planes to record and publicize all enemy moves.",
    "바다에 빠진 적군도 구조해주며 아군의 도덕적 우위를 과시합니다.": "Rescue drowning enemies to show moral superiority.",
    "국제 해양법을 어기는 적의 행동을 낱낱이 기록해 국제 재판소에 제소합니다.": "Record all enemy maritime law violations for international court.",
    "해양 오염을 막는다는 명분으로 유조선의 통행을 제한적으로 통제합니다.": "Restrict tanker passage under pretext of preventing pollution.",
    "아군과 중립국들의 상선들이 공격받지 않게 안전 통로를 만들어 호위합니다.": "Escort friendly/neutral merchants through safe lanes.",
    "바다 위에서 오가는 모든 무전을 수집해 적의 의도를 파악합니다.": "Intercept all signals at sea to understand enemy intent.",
    "물포나 음향 대포를 사용해 적함을 손상시키지 않고 돌려보냅니다.": "Turn back enemy ships with water cannons/sonic guns, no damage.",
    "대형 부표나 그물을 설치해 배들이 물리적으로 접근하기 어렵게 만듭니다.": "Install large buoys/nets to make physical approach hard.",
    "공격받기 전에는 절대로 먼저 쏘지 않는 엄격한 수칙을 지킵니다.": "Strictly follow 'Do not fire unless fired upon'.",
    "적 함대와 아주 가까운 거리에서 나란히 항해하며 압박감을 줍니다.": "Sail very close to enemy fleet to create pressure.",
    "봉쇄 대신 특정 해역 통과 시 안전 보장 명목의 비용을 요구합니다.": "Charge 'safety fee' for passage instead of blockade.",
    "어선으로 위장한 배를 띄워 적 함대의 정보를 은밀히 수집합니다.": "Deploy spy ships disguised as fishing boats to gather info.",

    "사람이 직접 가지 않고 드론으로만 국경을 감시해 인명 피해를 막습니다.": "Monitor border only with drones to prevent human casualties.",
    "확성기로 아군의 방어 의지를 알리고 적군의 불법 행위를 지적합니다.": "Broadcast defense will and call out enemy illegal acts via loudspeakers.",
    "참호에서 서로 쳐다만 보며 먼저 쏘기를 기다리는 고도의 심리전을 펼칩니다.": "Stare-down from trenches, waiting for other to shoot first (Psychological).",
    "국경을 넘는 자들에게 최루가스나 고무탄을 쏴서 생명을 보존하며 막습니다.": "Use tear gas/rubber bullets on crossers to stop them without killing.",
    "충돌이 일어난 마을에서만이라도 싸움을 멈추기로 현장 지휘관끼리 합의합니다.": "Field commanders agree to local ceasefire in conflict village.",
    "중립적인 제3국의 감시원들을 국경에 초청해 투명성을 확보합니다.": "Invite 3rd party monitors to border for transparency.",
    "무너진 담장을 고치며 우리 땅을 지키겠다는 의지만 묵묵히 보여줍니다.": "Silently repair broken walls to show resolve to protect land.",
    "전쟁 중에도 국경을 넘는 외교관들의 안전을 보장해 대화의 끈을 놓지 않습니다.": "Ensure diplomat safety crossing border to keep dialogue alive.",
    "아군 병사나 민간인이 실수로 적진에 들어가지 않게 철저히 단속합니다.": "Strictly prevent friendly soldiers/civilians from accidentally crossing.",
    "국경에 대형 전광판을 설치해 아군의 번영과 평화 의지를 보여줍니다.": "Install huge billboards at border showing prosperity and peace.",
    "적군에게 고향 소식이나 노래를 들려주며 전투 의지를 약화시킵니다.": "Play hometown news/songs to weaken enemy fighting spirit.",
    "국경 인근의 특정 주파수만 재밍하여 적의 연락을 일시적으로 방해합니다.": "Jam specific border frequencies to disrupt enemy contact temporarily.",
    "시장을 닫아 적국 국경 마을의 생필품 수급을 어렵게 만들어 압박합니다.": "Close markets to cut supplies to enemy border towns.",
    "오히려 적군에게 국경을 같이 정찰하자고 제안해 오해를 줄입니다.": "Propose joint border recon to reduce misunderstandings.",
    "실수로 총이 발사되었을 때 즉시 사과하고 상황을 수습합니다.": "Immediately apologize and de-escalate if gun goes off strictly.",
    "누가 봐도 알 수 있게 국경선을 크고 분명하게 표시해 분쟁을 예방합니다.": "Mark border clearly so everyone knows, preventing disputes.",
    "적국에서 넘어온 탈영병을 인도적으로 대우하며 정보를 얻습니다.": "Treat deserters humanely and gain intelligence.",
    "아군과 적군 누구의 땅도 아닌 곳의 동태를 살펴 선점당하지 않게 합니다.": "Recon no-man's land to prevent enemy pre-emption.",
    "명절이나 기념일에는 국경의 경계 수위를 낮춰 평화의 제스처를 보냅니다.": "Lower alert level on holidays as a peace gesture.",
    "국경 근처에 평화 공원을 조성해 전쟁터가 아닌 공존의 장임을 강조합니다.": "Build peace park near border to emphasize coexistence.",

    "특정 하늘을 \"누구도 날 수 없는 곳\"으로 선포해 공습을 원천 차단합니다.": "Declare sky 'No-Fly Zone' to block airstrikes completely.",
    "공격용 무기 없이 고성능 카메라만 달고 적의 기지 배치를 촬영합니다.": "Equip only cameras, not weapons, to photograph enemy bases.",
    "언제든 장거리 비행이 가능하도록 급유기를 공중에 띄워두어 억제력을 보여줍니다.": "Keep tankers airborne to show long-range capability deterence.",
    "우주에서 적의 비행장 움직임을 감시해 이륙 사실을 미리 알립니다.": "Monitor airfields from space to warn of takeoffs in advance.",
    "거대한 레이더 기를 띄워 수백 킬로미터 밖의 적기를 미리 찾아냅니다.": "Launch giant radar planes to find enemy jets hundreds of km away.",
    "적의 전자 기기만 고장 내는 비살상 전자기파 공격을 준비합니다.": "Prepare non-lethal EMP to disable only electronics.",
    "적기가 다가오면 무전으로 즉시 퇴거를 요청하고 요격 의사를 밝힙니다.": "Warn approaching planes to leave immediately or face interception.",
    "적의 레이더 신호를 수집해 나중에 적 미사일을 교란할 데이터를 모읍니다.": "Collect enemy radar signals to gather data for future jamming.",
    "적기와 마주쳤을 때 사고가 나지 않게 국제 비행 규칙을 철저히 지킵니다.": "Follow international flight rules strictly to avoid accidents with enemy.",
    "인공 강우 등을 이용해 적 비행장의 시야를 일시적으로 가립니다.": "Use artificial rain etc. to blind enemy airfields strictly.",
    "수많은 소형 드론을 띄워 하늘의 작은 틈새까지 감시합니다.": "Launch many small drones to watch every gap in the sky.",
    "적기가 보이는 곳에서 아군 전투기가 화려한 곡예 비행을 하며 실력을 뽐냅니다.": "Perform aerobatics in enemy view to show off skill.",
    "격추되어도 인명 피해가 없는 무인기를 대량으로 띄워 적을 피곤하게 합니다.": "Launch mass UAVs (no casualty risk) to tire out the enemy.",
    "민간 항공기들이 전쟁에 휘말리지 않게 안전한 하늘길을 관리합니다.": "Manage safe skylanes so civilian planes don't get hit.",
    "적 전투기들 사이의 교신 내용을 도청해 작전 계획을 알아냅니다.": "Eavesdrop on enemy fighter comms to learn plans.",
    "병원이나 유적지 상공을 안전 구역으로 정해 폭격을 방지합니다.": "Designate hospitals/ruins as Air Safety Zones to prevent bombing.",
    "적기의 이륙부터 착륙까지 모든 경로를 기록해 국제 사회에 고발합니다.": "Record entire enemy flight path to report to world.",
    "산악 지형에서 통신이 끊기지 않게 하늘에 통신 중계기를 띄웁니다.": "Launch air relays to keep comms alive in mountains.",
    "적의 레이더를 잠시 먹통으로 만들었다가 풀어주며 기술적 우위를 경고합니다.": "Briefly jam enemy radar, then release to warn of tech superiority.",
    "최신형 스텔스기를 한 번씩 노출시켜 적이 함부로 덤비지 못하게 합니다.": "Expose stealth jets occasionally to stop enemy from acting rashly."
}

with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

for k, v in translations.items():
    content = content.replace(f'"{k}"', f'"{v}"')

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)

print("Translation part 2 complete.")
